ALPHA_SAMPLE_PLACES = [
    {
        "osm_id": 9_000_000_001,
        "name": "Tempelhofer Feld",
        "place_type": "park",
        "lat": 52.4736,
        "lon": 13.4035,
        "tags": {"cheap": True, "nature": True},
        "description": "Huge former airport field in Berlin, ideal for walks, bikes, and wide-open resets.",
        "region": "berlin-alpha",
    },
    {
        "osm_id": 9_000_000_002,
        "name": "Markthalle Neun",
        "place_type": "restaurant",
        "lat": 52.5022,
        "lon": 13.4318,
        "tags": {"cheap": True},
        "description": "Indoor market hall in Berlin with rotating food stalls and local vendors.",
        "region": "berlin-alpha",
    },
    {
        "osm_id": 9_000_000_003,
        "name": "East Side Gallery",
        "place_type": "cultural",
        "lat": 52.505,
        "lon": 13.4394,
        "tags": {"hidden_gem": True},
        "description": "Open-air stretch of the Berlin Wall turned into a riverside art gallery.",
        "region": "berlin-alpha",
    },
    {
        "osm_id": 9_000_000_004,
        "name": "Votivpark",
        "place_type": "park",
        "lat": 48.2158,
        "lon": 16.3605,
        "tags": {"nature": True},
        "description": "Compact Vienna park close to the Ring and easy to combine with museum days.",
        "region": "vienna-alpha",
    },
    {
        "osm_id": 9_000_000_005,
        "name": "Cafe Phil",
        "place_type": "cafe",
        "lat": 48.1986,
        "lon": 16.3576,
        "tags": {"cheap": True},
        "description": "Bookshop-meets-cafe in Vienna with a relaxed atmosphere for planning sessions.",
        "region": "vienna-alpha",
    },
    {
        "osm_id": 9_000_000_006,
        "name": "Belvedere Gardens",
        "place_type": "attraction",
        "lat": 48.1913,
        "lon": 16.3801,
        "tags": {"nature": True},
        "description": "Grand Vienna garden axis with skyline views and museum access nearby.",
        "region": "vienna-alpha",
    },
    {
        "osm_id": 9_000_000_007,
        "name": "Stanley Park Seawall",
        "place_type": "hiking",
        "lat": 49.3043,
        "lon": -123.1443,
        "tags": {"nature": True},
        "description": "Vancouver classic for long walking loops with water, skyline, and mountain views.",
        "region": "vancouver-alpha",
    },
    {
        "osm_id": 9_000_000_008,
        "name": "Granville Island Public Market",
        "place_type": "restaurant",
        "lat": 49.2712,
        "lon": -123.134,
        "tags": {"cheap": True},
        "description": "Easy food stop in Vancouver with lots of casual options in one place.",
        "region": "vancouver-alpha",
    },
    {
        "osm_id": 9_000_000_009,
        "name": "Kitsilano Beach",
        "place_type": "viewpoint",
        "lat": 49.2745,
        "lon": -123.1554,
        "tags": {"nature": True},
        "description": "Beachfront sunset spot in Vancouver with mountain and downtown views.",
        "region": "vancouver-alpha",
    },
]
